name: pconv-keras
channels:
- defaults
dependencies:
- h5py>=2.7,<3
- hdf5>=1.8,<2
- matplotlib>=2.2.0,<3
- mkl>=2018,<2019
- pip>=9.0.1,<=18.1
- python=3.6.*
- scipy=1
- pip:
  - black==18.9b0
  - colorama==0.3.9
  - Keras==2.2.0
  - numpy>=1.14.1,<=1.15.4
  - opencv-python==3.4.1.15
  - Pillow>=5.1.0,<=5.3.0
  - tensorflow-gpu>=1.8.0,<=1.9.0
  - tqdm==4.23.4
